force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/NoOfSections__c.field-meta.xml
<CustomField>
    <fullName>NoOfSections__c</fullName>
    <label>Number of Sections</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Section__c/Board_Section__c.object-meta.xml
<CustomObject>
    <label>Board Section</label>
    <nameField>
        <label>Board Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Section__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Board Sections</relationshipLabel>
    <relationshipName>Board_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BoardController.cls
public with sharing class BoardController {
    
    @AuraEnabled(cacheable=true)
    public static List<Board__c> getBoards(){
        try {
            List<Board__c>boards=[SELECT Id,Name,Description__c,NoOfSections__c FROM Board__c ORDER BY CreatedDate DESC];
            return boards;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

   @AuraEnabled
   public static string saveBoard(Board__c board,List<Board_Section__c>sections){
    try {
        insert board;

        for(Board_Section__c section:sections){
            section.Board__c=board.Id;
        }

        insert sections;
        
        return board.Id;
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
}